---
abstract: 'LWP::UserAgent interface but works using AnyEvent::HTTP'
author:
  - 'Yury Zavarin <yury.zavarin@gmail.com>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-HTTP-LWP-UserAgent
requires:
  AnyEvent: 5
  AnyEvent::HTTP: 2.1
  HTTP::Headers::Util: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  LWP::UserAgent: 5.815
  parent: 0
  strict: 0
  warnings: 0
version: 0.10
